### ISSUE TITLE
Sizing issues

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#100]
When the browser window is too narrow (and not really all that narrow), the text (org name, slogan) next to the logo on the main page disappears.

![image](https://user-images.githubusercontent.com/14303565/133830562-bca7951d-106c-4d1d-8ae8-a49a2bf9885e.png)

The Join US-RSE button also gets smooshed next to the search icon in the top menu.

**Comment by vsoch** [comment]
That's intentional - transitioning between the full site to the partial (e.g., likely a tablet) to a phone/mobile view, you can't fit all the elements. I wasn't sure of another better way to do it, but if someone wants to take a shot that would be great!

**Comment by cosden** [comment]
Related: Nav bar is too long. We could consider removing the word "Association" from the home "US-RSE Association" link. Or replace with a logo instead.

**Comment by cosden** [comment]
Once "fixed" we need to preview with other screen sizes to make sure nothing else looks odd.

**Comment by vsoch** [comment]
The easiest way to fix this is just to hide the buttons when the screen gets too small.
