### ISSUE TITLE
Change event timing from UTC to a US-based time zone

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#11]
It's not wrong to have them in UTC, but it would be my strong preference to list events in one of the 4 main time zones in the US. We are all used to converting in our head. Better yet, to have it displayed in local time.

**Comment by mtbc** [comment]
The event descriptions generated by Jekyll, I'm not aware of a way to use the browser's local timezone. However, the calendar currently picks up the that local timezone. How do you feel between,

1. Set Jekyll to a US timezone and leave the calendar alone, so the event pages may show a different time from the calendar.
1. Set Jekyll and the calendar to the same US timezone which may not be the user's local one.
1. Have someone else see if they have any tricks to have Jekyll apply the user's local time.

...?

**Comment by vsoch** [comment]
Transferred to https://github.com/USRSE/usrse.github.io/issues/525.
