### ISSUE TITLE
Featuring Working Groups

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#12]
Where do we highlight working groups such as DEI? Or in the future other special interest groups?

**Comment by vsoch** [comment]
I had put a box at the end of the starting page (at least for DEI) linking to something that doesn't exist (but suggesting that it should), and another idea would be to have a menu for Working Groups that has submenus that take to specific pages for each one.

**Comment by cmaimone** [comment]
For now, I'd like to see a single Working Groups page under About or Get Involved that lists current working groups, short description, a contact, how to get involved, etc.  Then this main page can link to more specific pages if they are eventually needed with details on the work of each group.

Will need to ask each working group for info after we have a template of what we want to include.

**Comment by vsoch** [comment]
@cmaimone I can put together this starter page - that's a good idea to have a single page to start, and expand after that.
