### ISSUE TITLE
Links Page under Training should be under External

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#14]
The links on the Training > Links page aren't really training resources.  This seems like a better fit under external.

This page also has different types of things that need to be cleaned up. 
1. Links to other organizations we want people to know about
2. Maybe a few learning links - but these should link to specific training materials if they exist, not just the organizations -- be organized more.  Maybe outsource this to the Training/Education working group 
3. RSE community resources

**Comment by cmaimone** [comment]
I've pinged the education/training working group to decide on #2 -- if we should have such a page on the website, and if so, what the content should be

**Comment by mtbc** [comment]
Did anything come of (2), @cmaimone, or best to just try to decently clean/organize the ones we have?

**Comment by vsoch** [comment]
hey @mtbc any updates here?

**Comment by mtbc** [comment]
No, though when I last looked at the page, it did look like I should be able to guess a bit at some improvement.

**Comment by vsoch** [comment]
I'd be happy with just copy pasting the current page and adding to the repo via PR, and we can discuss improvements to the page itself post-live.

**Comment by mtbc** [comment]
> This seems like a better fit under external.

The external links open in a new tab. Ought this also?

**Comment by vsoch** [comment]
Yes, external links (that make the user leave the site) should be opened in another tab.

**Comment by mtbc** [comment]
Ah, the links page itself is internal though, okay.

**Comment by mtbc** [comment]
Hmmm, are things like https://usrse.github.io/blog and https://usrse.github.io/usrse-map "leaving the site"?

**Comment by vsoch** [comment]
yeah they are technically different sites (and especially now the branding is different).

For the links I misunderstood - the links page itself should not be external as it's part of the site.

**Comment by vsoch** [comment]
"External" does not mean "A page on the site with links to other resources" it means literally "a list of links that take you off of this site" so the links page itself does not belong there. Apologies for not catching this earlier!

**Comment by mtbc** [comment]
Aha, okay. Should we maybe consider putting the links page under External, as this issue seems to suggest? It's an internal page but just links to a bunch of external stuff, might be nice to have a few submenu items per heading if the semantics allow.

Re. this issue's description, given the lack of training links from (2), I wonder if the two lists currently on the page could be split into two pages, e.g., Organizations and RSE Resources, it feels a bit tidier then. If they still deserve their own heading, not sure what to call it though I agree Training probably isn't it.

**Comment by vsoch** [comment]
I don't think so, I think it belongs under resources. But we should probably have a better organization / structure of resources on the site so it's not just a page with external links.

**Comment by vsoch** [comment]
And agree - links and training are weirdly grouped together and probably should be flushed out!

**Comment by mtbc** [comment]
Happy to leave this issue open as a placeholder for poking the education/training working group. I like the idea of making those links a third menu item as in https://github.com/vsoch/usrse.github.io/pull/55#issuecomment-884971588.

**Comment by cosden** [comment]
The first iteration of the E&T group's training links page is now PR #66
