### ISSUE TITLE
Community Documents

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#19]
https://vsoch.github.io/usrse.github.io/community-documents/ - I find this page confusing.  I suggest starting with a list of community documents with short descriptions, and possibly their status?  In progress, planning, draft done, etc.  

Also would like to see more explanation on what the goal of the community document is -- resource for the community, resource for outsiders, etc.  The goals could be different for each document, or overall, what is the goal of having community documents?  What need is this meeting?

The how do I edit/how do I start a document content seems a little detailed/specific for what is kind of a top level page.

**Comment by cmaimone** [comment]
"Community Documents" appears in two places: direct link under external (which I understand why it's there, but don't know that others will), and under Get Involved.  

I suggest removing the page under Get Involved, and just directly linking to the community docs site instead.  Is there a different name we might use for these though?  Maybe Community White Papers?  When I see "Community Documents" I think of something more like: https://github.com/USRSE/documents - our official documents

**Comment by cmaimone** [comment]
Discussed in working group (notes):
- possibly renaming to community white papers or some other name instead of documents to capture what it is
- link under Get Involved instead of external
- Page on website about what the effort is, maybe link to "done" documents (if there are any), but move details to the repo on how to contribute, etc. -- frame as one community activity that people can get involved in

**Comment by vsoch** [comment]
This should be addressed in #45 and the wiki title is already named.

**Comment by vsoch** [comment]
Fixed!
