### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#20]
Have a clearer contact page/contact info probably in the footer and perhaps in the About section.  Primary contact is contact@us-rse.org.

**Comment by mtbc** [comment]
Could some kind of mail envelope with a `mailto:contact@us-rse.org` link be good in the footer, along with the social media icons, or would that be confusing? Is there an obvious source of SVG like the others?

**Comment by vsoch** [comment]
This is done - we now have a simple contact page and an icon with link in the footer. Thanks @cmaimone !
