### ISSUE TITLE
License for content

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#25]
On the old page we had a footer that made licensed content as CC BY 4.0:
![image](https://user-images.githubusercontent.com/5824618/118568415-c7f0b700-b745-11eb-9bb1-1d33736926bd.png)

There was some brief discussion in #23 but we likely need to have a broader discussion about what is appropriate.

**Comment by vsoch** [comment]
We discussed in the working group - we are going to have a frontend matter boolean that indicates pages that should have this copyright (e.g., mostly community pages, not anything where there might be a contributor talk, paper, etc.)

```yaml
copyright: true
```

**Comment by vsoch** [comment]
And we would want to say that copyright for the main site content is this attribution, but copyright for included material remains with contributors.

**Comment by vsoch** [comment]
Transferred to https://github.com/USRSE/usrse.github.io/discussions/523
