### ISSUE TITLE
Top Menu links: currently go to home page

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#27]
The top menu links (About, Events, Get Involved, etc. ) are currently linked to the main page instead of section-specific pages.  Need to decide if these go to some type of section index or one of the subpages.  

For example, if you click on Careers, where should it go?

**Comment by mtbc** [comment]
Alternatively, maybe don't make them links if the submenu has all that's needed.

**Comment by vsoch** [comment]
Yeah this seems more like a bug, I can try fixing it.
