### ISSUE TITLE
Job board: posting policy

### ISSUE THREAD

**Issue by cmaimone** [vsoch/usrse.github.io#29]
We might have this somewhere, but link more clearly from the job board a policy as to what is appropriate to be posted.  We might need to write or refine this policy.

**Comment by mtbc** [comment]
Would it be worth asking in Slack or is it obvious who would know if there is already a policy or, absent one, who would generate it? We could sure try to draft one if it'd not tread in another's bailiwick.

**Comment by vsoch** [comment]
Done! https://vsoch.github.io/usrse.github.io/jobs/policy/
