### ISSUE TITLE
Home in navbar

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#31]
When I preview the new website locally the home link in the navbar is gone (as expected from #23): 
![image](https://user-images.githubusercontent.com/5824618/118738735-b7a80d00-b815-11eb-8c8b-3ff633d9af9e.png)

But the published version it’s still there:  
![image](https://user-images.githubusercontent.com/5824618/118738767-cb537380-b815-11eb-90e3-32db669ed15b.png)

Am I missing something obvious?

**Comment by vsoch** [comment]
oh oups, that's my fault! I disabled all actions (of which page building is one) so we wouldn't be parsing for expired jobs, updating contributors, etc. I just changed the settings to allow GitHub based actions, so (I think?) that should work to trigger a build. We can double check the next time the site is merged to master.

**Comment by vsoch** [comment]
When you need to check, you can check the pages builds here: https://github.com/vsoch/usrse.github.io/deployments/activity_log?environment=github-pages

**Comment by vsoch** [comment]
I think we can close this one.
