### ISSUE TITLE
Bug with expired job on jobs page

### ISSUE THREAD

**Issue by exoticDFT** [vsoch/usrse.github.io#32]
It also seems like we may have a bug? We updated the jobs file last week to match us-rse.org, but https://vsoch.github.io/usrse.github.io/jobs/ and https://us-rse.org/jobs/ don't match up. And more specifically, the postings that aren't working seem to have expiration dates that have passed. One example, https://github.com/vsoch/usrse.github.io/blob/c72c67e75d0e98abfc77f29717936e0f270b4c64/_data/jobs.yml#L39-L42

_Originally posted by @exoticDFT in https://github.com/vsoch/usrse.github.io/issues/30#issuecomment-844585624_

**Comment by vsoch** [comment]
There's no reason they should - the updates have to be done manually. Also, the usrse repo has a job that explicitly removes expired jobs (this repo does not, at least I disabled it).

I don't think we should worry about automation here, because we aren't running it here. It's a distraction from working on content and layout of the site.

**Comment by exoticDFT** [comment]
I'm not sure I follow entirely. The usrse repo is running some automation to remove the expired jobs and we currently have that off for this fork. However, was this automation removing "dead links" or using the "expires" label of the postings? I'm just a little confused on why the pages don't match, since the jobs.md file seems to just reference the "expires" label to decide how the html is populated.

If we wanted to add a "posted on" label to our jobs.yaml and we update the layout on jobs.md, as mentioned in #30, will this show up on https://vsoch.github.io/usrse.github.io/jobs/?

**Comment by vsoch** [comment]
I honestly wouldn't worry about it - when it's time to deploy for the actual site we can just copy paste the correct file :)

**Comment by vsoch** [comment]
Also, the site that's online here hasn't been built for about 23 days. I had disabled GitHub actions, but should be enabled now.

**Comment by vsoch** [comment]
see https://github.com/vsoch/usrse.github.io/issues/31

**Comment by exoticDFT** [comment]
> Also, the site that's online here hasn't been built for about 23 days. I had disabled GitHub actions, but should be enabled now.

This is the piece I wasn't understanding. I thought the website had been rebuilt when you made the commit to "Sync with usrse...". I'll close this issue then.
