### ISSUE TITLE
Future RSE groups page

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#37]
https://us-rse.org/rse-groups/

What becomes of this page? I'd suggest it either needs to be updated/expanded (significantly) or removed. 

I'd like it to be the latter, so if it is, then it needs more content. Perhaps we don't need permission/approval to post there, just knowledge that a formal group exists.

**Comment by mtbc** [comment]
Definite :+1: to preserving but adding content. I could post in `#general` asking people if they're in such a group and, if so, let me know details and I'll open a PR. But, to minimize later merge issues, better against this repo, and people can be okay to wait to be added? Or best to wait to even ask?

**Comment by mtbc** [comment]
My current intent is to ask in Slack then update this fork accordingly by adding the groups people mention. If anybody would prefer me to do differently, say so soon.

Also, am I right in thinking that this fork doesn't even have that page? Would it maybe go under External?

**Comment by mtbc** [comment]
Now asked in https://usrse.slack.com/archives/C8ZB01CGH/p1624038092116700.

**Comment by mtbc** [comment]
@danielskatz mentions that the NCSA link will need updating.

To add: RSE group at Brown University, in the [Center for Computation and Visualization (CCV)](https://ccv.brown.edu/).

Also, I can probably extend the ORNL entry.

**Comment by cosden** [comment]
Some others off the top of my head that aren't there currently that I think we should also include (perhaps after checking with someone) Sandia, University of Alabama, Ohio Supercomputing Center, and Indiana University.

**Comment by mtbc** [comment]
:+1: I spent years working a very short walk from OSC.

**Comment by vsoch** [comment]
@mtbc do you need any help here?

**Comment by mtbc** [comment]
I *might*, yet to get to trying to make this happen. If anybody wanted to take on more of the liquid scripting side, I can sure try to gather groups in some `_data/*.yml`, otherwise more likely to get to #14 before this one.

**Comment by suednimh** [comment]
I have sent requests to 3 groups at the University of Wisconsin-Madison that provide research software/data science support. I asked permission to list their groups, and if they have a preferred page link and/or contact.

**Comment by mtbc** [comment]
I should be able to open a PR here before we next meet, it's looking easier than I'd initially feared since @vsoch pointed me to useful material on the previous site that we fork this from. Please do feel free to add any more groups to the Slack thread and this issue and I'll include them as I go, then we can tweak styling accordingly.

> Would it maybe go under External?

Under the present draft, I'm thinking "Resources": Related Organizations vs (this) Organizations with RSEs.

**Comment by suednimh** [comment]
You're way ahead of me, then. I just managed to get Jekyll spun up in a Docker container.  

I think we are both seeing that there are two types of Organizations. If you are planning to maintain both pages with different titles under Resources, I think that's a great idea. Or put them on one page with 2 sections, one for each type. 

Have you pushed a copy of your branch to Github? That way I could pull what you have done and follow along with your changes as I learn to understand Jekyll...

**Comment by mtbc** [comment]
Yes, two pages with different titles, seems the best I can figure right now. I'll let you know when I tidy and push! With luck I'll be able to make it to more meetings again soon too, happened to have unlucky exceptional clashes lately.

**Comment by mtbc** [comment]
@suednimh: I have opened PR #88 which shows where I am up to. I'll be happy to try to fix it according to what people think or to help you do so.

Some points:
* It's been suggested that there are probably links to add or adjust for:
  - Sandia
  - Ohio Supercomputing Center
  - Indiana University
  - UW Madison
  - NCSA
* My current branch introduces its own CSS as I had trouble figuring how to work with the existing site's.
* I'd like to elide repeated institutions with a `rowspan`.

Those may all be post-live though.

**Comment by mtbc** [comment]
Those [last couple of points](https://github.com/vsoch/usrse.github.io/issues/37#issuecomment-899717871) can be addressed subsequently. I'll open one for the first.

**Comment by mtbc** [comment]
Opened #91 about adding the further RSE groups.
