### ISSUE TITLE
Spelling out of US-RSE Association

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#5]
I realize the first time we see the US-RSE abbreviation is after the header and the events/about/news section. I'm not sure we're quite ready to assume people will know that's what it means. So maybe there is a way to work it in higher up.

**Comment by vsoch** [comment]
@cmaimone (I think, sorry if I mis-remember) was talking about having it in the text at the top instead of my corny slogan line. Is that an idea we want to try?

**Comment by cmaimone** [comment]
I think it wasn't about getting rid of the one-liner - we probably do want one.  It was just making sure we got the full name up at the top.  So along the lines of Ian's comment, perhaps spelling out the full name there - plus any tag line we come up with.

**Comment by vsoch** [comment]
Gotcha! So for the next round of changes I'll try adding the full name (and my terrible one liner, and we can figure out a better one later!)

**Comment by cosden** [comment]
I agree that we likely want a one liner. If there is a way to spell out US-RSE and have a one liner, that would be ideal. 

I don't think the one you have is terrible or corny.  That said, let's make it its own issue so it's clear where that discussion should be.

**Comment by vsoch** [comment]
To clarify this issue - this will add the full name, but the actual line for the slogan can be discussed in another issue.
