### ISSUE TITLE
Decide on Single Sentence Description for front page header

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#7]
A single descriptive sentence or one-liner that describes US-RSE and our mission and organization would be a great design feature. 
We just need to decide on what it should be. I think it's a larger discussion than just the website wg.  

The one there now "Building software and community in support of research." is a great place holder!

**Comment by mtbc** [comment]
I'll ask beyond this issue but first let's see what we can figure out here.

* What other (imperfect) one-liners have people been toying with?
* What do people like and dislike about the current one-liner and any others?

Maybe I can find a way to take all that in and get us closer to where we want to be.

**Comment by mtbc** [comment]
Now asked in https://usrse.slack.com/archives/C8ZB01CGH/p1624037223114100.

**Comment by mtbc** [comment]
Some thoughts captured from Slack:

> I think it over emphasizes software (our members do that more than US-RSE does). I like words like: community, research software, together, grow, connecting, and building. I like “building” less because it sounds like it’s not done. While that’s true, and has a positive connotation, we’ve built a lot already.

> - “A professional community for RSEs by RSEs,” (maybe spell out RSE)
> - “Connecting those who build research software,”
> - “A community to grow the Research Software Engineering Profession,”
> - “A community for RSEs to connect, learn, and grow,”
> - “Building community and research software, together”
> - “Building a community of research software engineers.”

**Comment by mtbc** [comment]
Having mused on the above, I'm currently toying with a working draft of,

> Connecting the people who make research software happen.

I'm going for,
* a community that brings RSEs together
* being vague enough to include anyone who reasonably fits as an RSE
* making RSEs sound useful and worthwhile.

Any thoughts, especially criticisms? I'm not convinced by the "make ... happen", though it sounds excitingly actiony, but I worry that "build ... software" might exclude those more into CI/server infrastructure or documentation/support or such? "build and support" would widen it...

(Of course, anything we much like, we can put in front of the wider community first, see if they concur.)

**Comment by vsoch** [comment]
I like it @mtbc ! I say go for it, because you asked for feedback and collected this result.

**Comment by mtbc** [comment]
![header](https://user-images.githubusercontent.com/2630707/126495031-dd32ed33-4772-40f5-8f82-5e705cd02944.png)
