### ISSUE TITLE
Bug: Sidebar menu labels (top link) link to vsoch.github.io

### ISSUE THREAD

**Issue by exoticDFT** [vsoch/usrse.github.io#78]
The news link in the top left of the news related pages goes to the wrong location.

![image](https://user-images.githubusercontent.com/18316938/128927318-62c8700c-4e1a-4bd6-b5ac-89b5afb9b622.png)

**Comment by cmaimone** [comment]
This is for all of the labels on the sidebar menus, not just the news page.  For example, also https://vsoch.github.io/usrse.github.io/join/ -- Engage with the Community

I can't figure out how to set the links for these.

**Comment by exoticDFT** [comment]
@cmaimone Great catch! I believe I found the problem and the where to fix it. Trying to figure out the correct URL variable to use. But right now it's set to go to `/`, which is V's main page.

**Comment by exoticDFT** [comment]
Mistake in "Get Involved" pages
