### ISSUE TITLE
Updates to Calendar Integration

### ISSUE THREAD

**Issue by cosden** [vsoch/usrse.github.io#8]
The new site's calendar (I think) pulls from the events page. This is useful functionality and makes a lot of sense. But it may end up with problems. Like the 2-day virtual workshop only shows up as one day and wouldn't be useful to import. 

Also how do we also best integrate the [us-rse google calendar](https://us-rse.org/calendar/)? (Right now we update the calendar manually to reflect new events. If on the new site calendar and events are integrated well, it may not be necessary.)

**Comment by vsoch** [comment]
@cosden the times are all customizable - if the two day workshop shows up as one day that's mostly my fault for adding the wrong timestamps - I had to go through every existing event and do it manually (start and end times).

And a google calendar can easily be added: https://fullcalendar.io/docs/google-calendar.

**Comment by vsoch** [comment]
Okay we're decided to try and phase out the Google calendar if possible - so we will start having the site just use events here, and assess if the Google Calendar would be needed after that (hopefully not!)

**Comment by vsoch** [comment]
Replaced with https://github.com/USRSE/usrse.github.io/issues/512
