### ISSUE TITLE
Discussion: Remove menu title pages from sidebar menus

### ISSUE THREAD

**Issue by exoticDFT** [vsoch/usrse.github.io#87]
After looking into issue #78 and talking with @vsoch. It seems like we have the "News and Updates" link in the sidebar menu, although the title for this menu lead us to this "main" page. The "About" sidebar menu does not have this extra link to itself.

We think it makes sense to follow the "About" menu design and remove the menu's main/title page from the menu itself, leaving it only as the title. We also need to reorganize the topbar items to be the same order as the sidebar.

Is there a better way to manage these menus, both for the topbar and sidebar? Can we have a single list that works for both?

**Comment by vsoch** [comment]
My bias is that each top level menu should be clickable, and clicking goes to the main page (that is accessed clicking the very top title of the sidebar navigation). This is exactly the "About" menu design.

**Comment by vsoch** [comment]
> Is there a better way to manage these menus, both for the topbar and sidebar? Can we have a single list that works for both?

Probably, but instead of targeting the menu exactly we'd need an index into the larger data structure that renders into the top menu. They don't always have to coincide 1:1 which is why I designed it like this, but you're right it's annoying to sync when you are making large changes.

**Comment by vsoch** [comment]
Transferred to main site as discussion! https://github.com/USRSE/usrse.github.io/discussions/517
